### ISSUE TITLE
Can I use integration ?

### ISSUE THREAD

**Issue by shinze** [codrops/css-reference-issues#11]

**Comment by crnacura** [comment]
I'm not sure what you mean, could you elaborate?

**Comment by shinze** [comment]
Sure, what I meant is to integrate a service as "Can I use" somewhere in the reference screen.

**Comment by crnacura** [comment]
Ah ok, yes, we actually do that for many entries, for example: http://tympanus.net/codrops/css_reference/animation-play-state/

Sara mentions more details on that in her article: http://tympanus.net/codrops/2015/02/03/introducing-codrops-css-reference/

Thanks for your feedback!
