### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yukulele** [codrops/css-reference-issues#15]
Hi,
This CSS references very complete, thank you for it!
I would like to know what kind of license is used for it. Is it possible to copy it as off-line version?

**Comment by crnacura** [comment]
Hi,
thanks a lot! The CSS reference entries have the same license as other articles on Codrops which states that it's not allowed to copy them, _in the sense of republishing them elsewhere_. What exactly do you mean with off-line version? Would you like to save the entries on your computer for later reading? If yes, then that should not be a problem.
