### ISSUE TITLE
Possible Typo on: http://tympanus.net/codrops/css_reference/font-size/

### ISSUE THREAD

**Issue by travisricks** [codrops/css-reference-issues#17]
Under Values > relative-size

> In addition to the above absolute keywords, two relative keywords **exits**: larger and smaller, which calculate the font size of an element relative to its parent’s font size. So, if, for example, the parent’s font size is set to large and the element’s font size is set to larger, the element’s font size will be x-large.

Is it supposed to be:

> In addition to the above absolute keywords, two relative keywords **exist**: larger and smaller, which calculate the font size of an element relative to its parent’s font size. So, if, for example, the parent’s font size is set to large and the element’s font size is set to larger, the element’s font size will be x-large.

P.S. This reference guide is very helpful. Thank you!

**Comment by crnacura** [comment]
Indeed, thanks a lot, Travis! I just fixed it :)
