### ISSUE TITLE
Entries To Add

### ISSUE THREAD

**Issue by SaraSoueidan** [codrops/css-reference-issues#18]
I've opened this issue to keep track of all additional concept entries that I want to add as soon as possible to the reference. These entries include:
- [x]  attribute selectors
- [x]  media queries (including different possible conditions, etc.)
- [x]  Combinators
- [x] `all` property entry
- [x] `appearance` property entry

The list will be updated with other entries when necessary and, of course, comments and more suggestions are welcome in the comments!

**Comment by SaraSoueidan** [comment]
+ Add `all` property entry :: http://dev.w3.org/csswg/css-cascade/#all-shorthand

**Comment by SaraSoueidan** [comment]
Add the `unset` keyword entry.

**Comment by crnacura** [comment]
Moving this to #76
