### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by fvignals** [codrops/css-reference-issues#24]
1.Work on all desktop browsers. (not on Android)
2.<p lang="en"> works.
3.Your exemple is bad : your text isn't english ! Browsers use an internal local dictionary. (so I didn't have test all languages, work fine in english, french and I think all latins language).
4. I should update CanIuse : 
- Opera 27.0.1689.69 support the 3 values.
- Firefox 35.0.1 support the 3 values.
  my test : http://codepen.io/fvignals/full/azYexa

good work :)

**Comment by crnacura** [comment]
Thanks for the feedback! We've fixed it now :)
