### ISSUE TITLE
Spelling Error - [droo-shadow] 

### ISSUE THREAD

**Issue by Vince-Smith** [codrops/css-reference-issues#30]
<a href="http://tympanus.net/codrops/css_reference/filter/#section_drop-shadow" > Filter Reference Line: 658 </a> has a spelling error. <code>droo-shadow</code> should be <code>drop-shadow</code>.

**Comment by botelho** [comment]
Thanks a lot! Fixed!

**Comment by Vince-Smith** [comment]
No problem!
