### ISSUE TITLE
Flexbox reference: tweaks to illustrations maybe

### ISSUE THREAD

**Issue by fvsch** [codrops/css-reference-issues#31]
Hello,

I didn't have time to carefully read all the Flexbox reference at http://tympanus.net/codrops/css_reference/flexbox/, so I've mostly skimmed it, but I've noticed a few things with the illustrations:

Typos:
- [order-illustration](http://codropspz.tympanus.netdna-cdn.com/codrops/wp-content/uploads/2014/10/order-illustration.jpg) is missing a closing parenthesis.
- [align-self-illustration](http://codropspz.tympanus.netdna-cdn.com/codrops/wp-content/uploads/2014/10/align-self-illustration.jpg) is missing a "e" in "baseline" ("basline").

One imprecision:
-   [flex-grow-illustration](http://codropspz.tympanus.netdna-cdn.com/codrops/wp-content/uploads/2014/10/flex-grow-illustration.jpg) suggests that the values for the third example are: `flex-grow: 0` for the first and last item, and `flex-grow: 2` for the middle item. The text after the illustration makes it clear that the first and last items have `flex-grow: 1`, but the illustration can be misleading. My suggestion: add another line of text before the third example, so that the label reads:
  
  > flex-grow: 1 (all)
  > flex-grow: 2 (on second item)

Congrats again on all the excellent work in this reference.

**Comment by crnacura** [comment]
Thanks a lot, fixed!
