### ISSUE TITLE
Firefox issue with backface-visibility

### ISSUE THREAD

**Issue by ninjasort** [codrops/css-reference-issues#32]
This first example shows the text through the backface on Firefox 34.0.5. I have a similar plugin with the same issue. Any ideas for a fix? http://tympanus.net/codrops/css_reference/backface-visibility/

**Comment by crnacura** [comment]
Thanks @cameronjroe!

@SaraSoueidan could you have a look, I can confirm the issue. Could be a bug :/ And it looks like we don't need the JS in this demo?
