### ISSUE TITLE
Typo in the embedded caniuse info box?

### ISSUE THREAD

**Issue by tieneguasa** [codrops/css-reference-issues#37]
Hello Sara!
First of all, I love your work and I thank you for share it with us!

I don't know if this is really an issue, it is only a typo, but it appears in every embedded caniuse info box:
At the bottom of the info box there are always a couple of links:
"Compatibility table provided by Can I use... — Seperate page — About embedding "
I think, it should be "Separate page". Sorry, I'm absolutely not picky, but as I saw it I thought that if it really is a typo, you could want to know it.

Have a nice day and thank you again!
Alberto

**Comment by SaraSoueidan** [comment]
HI Alberto

Thank you so much for your comment — you don't have to apologize for pointing out a typo!

That said, that's a typo on the caniuse.com site, not something we can fix on Codrops.

Maybe you could tweet @Fyrd on Twitter to fix this?

Cheers,
Sara
