### ISSUE TITLE
Incorrect numbering of Flexbox items in image

### ISSUE THREAD

**Issue by freakyleaf** [codrops/css-reference-issues#4]
Page: http://tympanus.net/codrops/css_reference/flexbox/
Image: http://codropspz.tympanus.netdna-cdn.com/codrops/wp-content/uploads/2014/10/flex-direction-illustration.jpg

The 'column reverse' numbers featured on the 'flex direction' image should be listed from high to low. Currently they're listed the same as the 'column' numbers.

**Comment by SaraSoueidan** [comment]
Fixed! Will update online image shortly.

Thank you very much for the heads up! :)

Cheers!
-Sara
