### ISSUE TITLE
Intro to CSS functions?

### ISSUE THREAD

**Issue by fakefarm** [codrops/css-reference-issues#40]
Thank you for taking the time to compile this reference. It serves as a great guide to deepen my understanding of CSS! I have not been using css functions at all. I didn't see anything on [codrops](http://tympanus.net/codrops/?s=css+functions&search-type=posts) and when I google for them I encounter JQuery's `css()` or `LESS` examples. 

Can you point me to a place to a general intro to css functions? 

Thanks again!

**Comment by SaraSoueidan** [comment]
LESS is a CSS preprocessor, and such functions are not part of CSS.

Functions in CSS include `linear-gradient()`, `element()` and a few others, but `css()` is is a jQuery method that allows you to set CSS properties via JavaScript. I think the jQuery docs would be the best place to find more about this and/or google any articles setting CSS properties using jQuery. 

I'm sorry I don't use jQuery much so I don't have any resources at hand.

LESS, on the other hand, is another story. Most people today prefer Sass for its capabilities. [This article](http://www.smashingmagazine.com/2011/09/an-introduction-to-less-and-comparison-to-sass/) is an intro to the first and  it compares it to Sass, so you might find it useful.

Hope that helps!
