### ISSUE TITLE
timing-function_value article

### ISSUE THREAD

**Issue by seyedi** [codrops/css-reference-issues#43]
In the last demo the third transition function is step-start but it's written step-end. please check it. thanks.

**Comment by SaraSoueidan** [comment]
Indeed, thanks for catching that!

@crnacura I can’t access the demo editor, could you please fix that? either change the `step-end` keyword in the HTML or the `step-start` in the CSS? Thank you <3

**Comment by crnacura** [comment]
@SaraSoueidan Ah yes of course!! I've fixed it :) Thanks :)

**Comment by SaraSoueidan** [comment]
<3
