### ISSUE TITLE
::first-line --- first heading is about "::first-letter"

### ISSUE THREAD

**Issue by pmmueller** [codrops/css-reference-issues#45]
On the page about [::first-line](http://tympanus.net/codrops/css_reference/first-line/) the first heading reads "Properties used to style ::first-letter". 

That should probably be "Properties used to style [b]::first-line[/b]". 

And a million thanx for this stellar CSS reference!

**Comment by SaraSoueidan** [comment]
Fixed. Thank you!

And thank you very much. =)
