### ISSUE TITLE
calc function

### ISSUE THREAD

**Issue by seyedi** [codrops/css-reference-issues#48]
Hi, in the section below it's said "left margin of an element to be ‘10%’ of its width" however it is 10% of its container not the element itself.

![calc](https://cloud.githubusercontent.com/assets/2035789/12291898/15e70332-b9ff-11e5-801c-479ab3d991d8.PNG)

You can check it [here](http://jsbin.com/nuniputodi/edit?css,output) quickly.

Thanks again for your great reference :+1:

**Comment by crnacura** [comment]
Thanks a lot, fixed :)
