### ISSUE TITLE
wrong spelling

### ISSUE THREAD

**Issue by aleen42** [codrops/css-reference-issues#49]
- In the page [http://tympanus.net/codrops/css_reference/default](http://tympanus.net/codrops/css_reference/default), you'll find that there is a wrong spelling on the sentence, "Buton inputs and buttons of type="submit" are considered one group, and therefore the first of them is the default". "Button" has missed a cute character '**t**'.

**Comment by aleen42** [comment]
- “Comments and and processing instructions do not affect whether the element is empty or not. ” has an unexpected "and" in [http://tympanus.net/codrops/css_reference/empty/](http://tympanus.net/codrops/css_reference/empty/)

**Comment by crnacura** [comment]
Fixed, thanks!
