### ISSUE TITLE
::before blockquote sample code doesn't match live example

### ISSUE THREAD

**Issue by lukeruth** [codrops/css-reference-issues#5]
In the ::before article (http://tympanus.net/codrops/css_reference/before/) the blockquote example sample code has the ::before element listed with a font-size of 2em, but in the live code it has a font-size of 3em.

Additionally, the sample code has a top value of 5px but the live example has a top value of 20px. Obviously this is a small issue but just wanted to bring itup.

**Comment by SaraSoueidan** [comment]
Fixed! 

Thank you Luke! :)

Cheers!
-Sara
