### ISSUE TITLE
Typos in Flexbox reference

### ISSUE THREAD

**Issue by prayagverma** [codrops/css-reference-issues#52]
Hi, while reading http://tympanus.net/codrops/css_reference/flexbox/ , I came across the following typos -

Attaching screenshots with each so that they are easier to find -
1. Spelling mistake - `ptoperty` > `property`
   ![ptoperty](http://i.imgur.com/K5wyFg1.png)
2. Remove extra `by` 
   ![extra by](http://i.imgur.com/ZrlJOiB.png)
3. Spelling mistake - `realtive` > `relative`
   ![realtive](http://i.imgur.com/42O4fpn.png)
4. Remove extra `for`
   ![extra for](http://i.imgur.com/lK7Q8Zq.png)

**Comment by crnacura** [comment]
Thanks so much, all fixed!
