### ISSUE TITLE
Some typos 

### ISSUE THREAD

**Issue by prayagverma** [codrops/css-reference-issues#56]
Hi, I opened a few issues about typos before. This is a consildated issue of some other typos I came across. I don't want to disrespect or offend anyone just want to improve the CSS Reference .

Here is the list of typos -

In http://tympanus.net/codrops/css_reference/font-face/
1. Spelling mistake - `Scalabe` > `Scalable`
   ![Scalabe](http://i.imgur.com/2onIUec.png)
2. Replace `the these` with `these`
   ![the these](http://i.imgur.com/9xWtDBP.png)

In http://tympanus.net/codrops/css_reference/keyframes/
1. Spelling mistake - `mising` > `missing`
   ![mising](http://i.imgur.com/GSnygCJ.png)

In http://tympanus.net/codrops/css_reference/namespace/
1. Spelling mistake - `delcare` > `declare`
   ![delcare](http://i.imgur.com/Gtk2T3h.png)

In http://tympanus.net/codrops/css_reference/supports/
1. Spelling mistake - `parantheses` > `parentheses` ( 4 instances )
   ![parantheses](http://i.imgur.com/YPLEWAL.png)
2. Spelling mistake - `combinning` > `combining`
   ![combinning](http://i.imgur.com/ivIPGZb.png)

In http://tympanus.net/codrops/css_reference/timing-function_value/
1. Spelling mistake - `abrubtly` > `abruptly`
   ![abrubtly](http://i.imgur.com/AIuMtzW.png)

In http://tympanus.net/codrops/css_reference/percentage/
1. Replace `an` with `a`
   ![replace an with a](http://i.imgur.com/WNrrG3X.png)

In http://tympanus.net/codrops/css_reference/number/
1. Replace `an` with `a`
   ![replace an with a](http://i.imgur.com/8PPDf1r.png)

In http://tympanus.net/codrops/css_reference/image/ 
1. Spelling mistake `intsinric` > `intrinsic` ( 5 instances)
   ![intsinric an with a](http://i.imgur.com/M2UN4lL.png)
2. Space between `::after` and `and`
   ![add space between and](http://i.imgur.com/VwXHmbi.png)

In http://tympanus.net/codrops/css_reference/color_value/
1. Spelling mistake - `Summerized` > `Summarized`
   ![Summerized](http://i.imgur.com/zjHUQEH.png)

In http://tympanus.net/codrops/css_reference/blend-mode/
1. Spelling mistake `monchrome` > `monochrome`
   ![monchrome](http://i.imgur.com/opLOSeJ.png)

In http://tympanus.net/codrops/css_reference/basic-shape/
1. Spelling mistake - `preceeded` > `preceded`
   ![preceeded](http://i.imgur.com/W0dca63.png)

In http://tympanus.net/codrops/css_reference/repeating-radial-gradient/
1. Remove extra `be`
   ![extra be](http://i.imgur.com/VQ7HLzO.png)

In http://tympanus.net/codrops/css_reference/radial-gradient/
1. Spelling mistake - `ore` > `or`
   ![ore](http://i.imgur.com/IY5v5dn.png)

In http://tympanus.net/codrops/css_reference/linear-gradient/
1. Spelling mistake - `ore` > `or`
   ![ore](http://i.imgur.com/iv2DjoZ.png)

In http://tympanus.net/codrops/css_reference/inset/
1. Spelling mistake - `preceeded` > `preceded`
   ![preceeded](http://i.imgur.com/FIlaI7n.png)

In http://tympanus.net/codrops/css_reference/hsla/
1. Replace `hsl()` with `hsla()`
   ![hsl](http://i.imgur.com/ATDZx8x.png)

In http://tympanus.net/codrops/css_reference/hsl/
1. Spelling mistake - `Summerized` > `Summarized`
   ![Summerized](http://i.imgur.com/lAsYsvs.png)

**Comment by crnacura** [comment]
Thanks so much, we really appreciate it!! Will correct them as soon as possible :)

**Comment by crnacura** [comment]
All done! Thanks again!
