### ISSUE TITLE
Spell wrong

### ISSUE THREAD

**Issue by aleen42** [codrops/css-reference-issues#58]
- Problem Sentence: There is a pseudo-class selector that has a similar functionality to that of :nth-last-child(), that selector is the **:nth-hild()** selector. :nth-child() is similar to :nth-last-child, except that it iterates through the elements from the first element down to the last one.
- Spelling wrong in the page: [http://tympanus.net/codrops/css_reference/nth-last-child/](http://tympanus.net/codrops/css_reference/nth-last-child/)

**Comment by crnacura** [comment]
Thanks a lot, it's fixed now!
