### ISSUE TITLE
placeholder input type date

### ISSUE THREAD

**Issue by rianveal** [codrops/css-reference-issues#59]
Hi,
How to add or change placeholder a input type date?

thanks

**Comment by crnacura** [comment]
Hi, is this related to the Codrops CSS Reference http://tympanus.net/codrops/css_reference/ ?

**Comment by rianveal** [comment]
My question is based in this reference http://tympanus.net/codrops/css_reference/placeholder/

I'm wrong?

**Comment by crnacura** [comment]
Thank you. Please note that this repo is for collecting issues with the entries. Would you like to submit a suggestion for improvement or report an error in the entry?

**Comment by rianveal** [comment]
No thanks
