### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by seyedi** [codrops/css-reference-issues#60]
Hi, Can you help me with this please...

Is this statement correct?

> If an element is positioned absolutely and none of its predecessors have a positioning context, it is positioned relative to the <html> of the page.

Check this demo which the movement of html doesn't effect the position of our square till html has the position relative.

http://jsbin.com/zepopa/edit?html,css,output

so I think the element is positioned relative to the page not html.

Thank you so much for your great reference.

**Comment by crnacura** [comment]
Thanks, it should be viewport! Corrected.
