### ISSUE TITLE
Slip from top - admin theme - at dashboard

### ISSUE THREAD

**Issue by suriyaJaay** [codrops/css-reference-issues#62]
@crnacura can u help to fix the issue, am struggling it with for past 10 days and totally unable to understand where. and how change/control the css class.!!

the issue is.. am trying to implement your tymapanas niffty modal effect (slip from top effect) in my inspinia admin theme - in admin panal. i just need the exact effect for my product.

hope you help me

requirement: 
the even should trigger after clicking on of the menu appear when hover it from side menu bar.

**Comment by crnacura** [comment]
Since this is not a CSS reference issue, I'm going to close it. Please try to find help by commenting on the respective article/repo.
