### ISSUE TITLE
:read-only and :read-write

### ISSUE THREAD

**Issue by seyedi** [codrops/css-reference-issues#65]
For these two entries in browser support section following statement is not correct now as Opera supports `contenteditable` and these selectors.

> In Opera, elements that are editable using the contenteditable attribute are treated as read-only because it does not support the contenteditable attribute.

And also this one:

> In Chrome, elements editable using the contenteditable attribute do not match :read-only, and hence are not selected with :read-only. They don’t match the :read-write selector either—how they are treated is unknown. Same applies to regular elements that are not editable with contenteditable—they don’t match either of the two pseudo-class selectors.

Thanks.

**Comment by crnacura** [comment]
Thanks! Fixed!
