### ISSUE TITLE
<length> for translate3d tz and translateZ cannot be a % val

### ISSUE THREAD

**Issue by ankushdharkar** [codrops/css-reference-issues#66]
I was trying to use percentage for `tz` in `translate3d(tx, ty, tz)` and its shorthand `translateZ` and it didn't work

I looked around and saw that the MDN site for [translate3d](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate3d) and for [translateZ](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateZ) states:

>  It can't be a <percentage> value; in that case the property containing the transform is considered invalid.

Maybe a good idea to recheck them at:
http://tympanus.net/codrops/css_reference/transform/#section_translate3d
http://tympanus.net/codrops/css_reference/translatez/

**Comment by crnacura** [comment]
Absolutely, percentage values are not valid. Corrected and updated. Thanks a lot for opening the issue!
