### ISSUE TITLE
Padding Values section

### ISSUE THREAD

**Issue by clayton93** [codrops/css-reference-issues#67]
I have two slight niggles with this section:
- Trying to quickly look up the order of padding when you give four values and the last line says "If one value is provided, that value sets the fout padding sides (top, left, bottom, right)." Although it does say one value, the bit that stands out is the brackets with four values, not in the order that happens when four values are given. Not sure if there is a reason for this order but it is the first thing you may notice when looking at the big paragraph.
- Also four is spelt wrong in that sentence too - "sets the fout padding sides".

**Comment by crnacura** [comment]
Thanks, corrected!
