### ISSUE TITLE
Looks like some unnecessary spaces snuck in?

### ISSUE THREAD

**Issue by huphtur** [codrops/css-reference-issues#68]
noticed some odd spacing issues several pages: 

![spacers](https://cloud.githubusercontent.com/assets/469438/18058580/d59c42f4-6dc9-11e6-87aa-d27cf299fb42.png)

source: http://tympanus.net/codrops/css_reference/text-decoration/

**Comment by crnacura** [comment]
Thanks a lot! Fixed!
