### ISSUE TITLE
Attribute selectors

### ISSUE THREAD

**Issue by jamesfzhang** [codrops/css-reference-issues#7]
Unsure if [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) should be include here but I think they can be argued for. Also, I feel like many entry level designers and developers don't know about them.

**Comment by SaraSoueidan** [comment]
Certainly! That's a great idea. It would go with the Concepts section. We have a couple of entries we want to add to that section. I'll add this to the list and keep this issue open until we do it.

Thank you James!

Cheers!

**Comment by jeremyhicks** [comment]
Maybe a separate issue, but I was also thinking selectors could be included, specifically + > ~

**Comment by SaraSoueidan** [comment]
+1. Added to the list. Thanks Jeremy! :)

**Comment by SaraSoueidan** [comment]
I'm closing this issue in favor of another issue where I am collecting a list of new concept entries to add to the reference. See: https://github.com/codrops/css-reference-issues/issues/18
