### ISSUE TITLE
Example for backface-visiblity not working on Firefox on Linux

### ISSUE THREAD

**Issue by Gruximillian** [codrops/css-reference-issues#70]
Hi, first I want to thank you for the great article on [`backface-visibility`](https://tympanus.net/codrops/css_reference/backface-visibility/), and many others on Codrops.

I found out that on Fifrefox (50.1.0 - frefox for Manjaro) on Linux (Manjaro - Archlinux derivative), the example with flipping card does not work. The front side stays visible and mirrored.
I played a bit in your [live editor](https://tympanus.net/codrops-playground/SaraSoueidan/ayCnVaR0/editor) and found out that by commenting out the `z-index` properties for `.back` and `.front` classes the issue is resolved.
I have also tested that on Chromium (v55.0.2883.87) and Opera (v42.0.2393.94) on my system, and removal of the `z-index` does not affect the functionality.
I also tried this on Browserstack.com on Mac Sierra for the latest versions of Firefox and Chrome.
On Firefox on Mac the background gets changed but the text from the front of the card still shows through.
Again, I tried commenting out the `z-index` as I did on my machine, and the issue was resolved. That change did not affect the animation on Chrome, i.e. didn't broke it.

I understand why is the `z-index` used here, but it appears as if it is not needed. Maybe it is there for old browsers, but it would be good if it worked on the newest too.
On the other hand, this might be the Firefox bug, I don't know, but I just wanted to let you know about this issue.

All the best,
Vojislav Grujic

**Comment by crnacura** [comment]
Hi Vojislav,
I can't find any z-index defined for the front or the back in the live example... Where did you see that? Could you point me to the line? It's [this](https://tympanus.net/codrops-playground/SaraSoueidan/APZYoqfA/editor) example you are referring to, correct?
Thank you,
ML

**Comment by Gruximillian** [comment]
Hi, Mary
It's not in that example, I linked it in my comment, but it's not so obviuos, so here is the link again:
https://tympanus.net/codrops-playground/SaraSoueidan/ayCnVaR0/editor
It's the flip card with the kitten on it.

**Comment by crnacura** [comment]
Hi Vojislav,
I'm sorry I missed that link! I just checked and I can confirm that it doesn't work on Firefox on Mac. Removing those z-indexes works just fine, as you mentioned, so I'll take care of that as soon as possible. Thank you for pointing it out, very much appreciated,
best,
ML

**Comment by Gruximillian** [comment]
You are welcome. Codrops is a great inspiration and resource, and I was very glad to help.
Best regards,
Vojislav

**Comment by crnacura** [comment]
Thanks again, we've fixed it now! :)

**Comment by Gruximillian** [comment]
Cool! Keep up the good work! :)
