### ISSUE TITLE
Chrome: page-break-inside avoid with tables

### ISSUE THREAD

**Issue by bottasergio** [codrops/css-reference-issues#72]
page-break-inside:avoid, does it really works with tables in Chrome?

**< table style="page-break-inside:avoid" >
   ....
< /table >**

I can´t make it works in Chrome. Tables are always fragmented in 2 pages.

**Comment by crnacura** [comment]
I just tried this and it does seem to work: https://output.jsbin.com/fojisataba (print, and see the preview, the table is on the next page). Full example code: https://jsbin.com/fojisataba/edit?html,output

Note that you need to check on the parent's page-break-inside property, too, the 'page-break-after' property of the preceding element, and the 'page-break-before' property of the following element. In case the values are something else than 'auto', then 'always', 'left', and 'right' outweigh 'avoid'.
