### ISSUE TITLE
Links to Keyframes page from animation pages

### ISSUE THREAD

**Issue by clayton93** [codrops/css-reference-issues#73]
On the animation pages, apart from the "See also @keyframes" link in the header of animation pages, all other links to "@keyframes" take you to a 404 page.

The link it should go to is: `https://tympanus.net/codrops/css_reference/keyframes/`
but the link they go to is: `https://tympanus.net/codrops/css_reference/keyframes_rule`

**Comment by crnacura** [comment]
Thank you very much, all links are fixed now :)
