### ISSUE TITLE
css grid multiple grids.

### ISSUE THREAD

**Issue by brianran** [codrops/css-reference-issues#79]
Hi I am using css grid to redesign my large web site.
Can I use more than one grid on one page.
For Example if I am using placement by grid column and grid row numbers.
Chow can I then use minmax () function as well and how.
In susy you can have more than 1 grid layout, but I want to use css grid only.
Thanks for your great article have I missed something.
Brianran

**Comment by huijing** [comment]
I'm not sure if I understand you correctly but you can definitely have more than one grid on the page. They just need to have different class names. But if you're talking about subgrids, that does not exist yet, although it is possible to nest a grid within another, it's just that you cannot line the inner grid up with the outer grid automatically.

**Comment by brianran** [comment]
Thank you although I am only private Web Site developer for interest, I had in my head that setting a class could be the answer, and you confirm, I will now try and complete the page with your answer.
