### ISSUE TITLE
Transition-delay can't take multiple values

### ISSUE THREAD

**Issue by nagman** [codrops/css-reference-issues#81]
Hi,

I've read your [article on the transition-delay](https://tympanus.net/codrops/css_reference/transition-delay/), and it says it can take comma separated values.

But your third example doesn't work (the background animation is triggered at the beginning of the position animation, not at the end).

**Comment by crnacura** [comment]
Hi,
I just tried to adjust the delays and it works. The first value is for the background-color and the second one for the left:

```
.element-3 {
  -webkit-transition-delay: 0.5s, 2s;
  transition-delay: 0.5s, 2s;
}
```
Can you tell me what exactly you tried?
Thanks

**Comment by nagman** [comment]
Hi,
My bad, I just didn't understand the text.
I thought the background should animate when the position has finished to
animate.

2017-09-20 13:19 GMT+02:00 Mary Lou <notifications@github.com>:

**Comment by crnacura** [comment]
Thanks for clarifying :)
