### ISSUE TITLE
table-layout code example mistake

### ISSUE THREAD

**Issue by Yuyz0112** [codrops/css-reference-issues#83]
In the table-layout(https://tympanus.net/codrops/css_reference/table-layout/) reference's 'The Automatic Table Layout' section, there is a mistake in the code example's class name.

> If the width of the table is set, the widths of the columns are set, and the width of the columns is less than the width of the table, the remaining white space is distributed among the columns evenly.

code example: https://tympanus.net/codrops-playground/SaraSoueidan/1KYzzIAk/editor

I think the the second `td` should has a class name of 'col-2'.
```diff
- <td class="col-1">width of second column is 200px</td>
+ <td class="col-2">width of second column is 200px</td>
```

**Comment by Yuyz0112** [comment]
Update: another typo
code example: https://tympanus.net/codrops-playground/SaraSoueidan/mf1yAf18/editor
```diff
.col-3 {
-  width: 200px;
+  width: 100px;
}
```

**Comment by botelho** [comment]
Fixed! Thanks a lot!
