### ISSUE TITLE
Position property

### ISSUE THREAD

**Issue by janriemer** [codrops/css-reference-issues#86]
Hi,
in the article on [the position property](https://tympanus.net/codrops/css_reference/position/) in the section _Trivia & Notes_, I've seen a small mistake when the article talks about absoulutely positioned elements and their height:

>  Similarly, an **absolutely** positioned element can be stretched vertically using top and bottom offset
> properties, and leaving height unspecified.
> ```
> position: relative; <-- this should be absolute
> top: 0;
> bottom: 0;
> ```

Thanks for the very good css reference and your effort! 🤗

**Comment by crnacura** [comment]
Thanks so much, it's fixed now!
