### ISSUE TITLE
Grid: typo in line-names

### ISSUE THREAD

**Issue by wiiiiilllllll** [codrops/css-reference-issues#89]
In the section [https://tympanus.net/codrops/css_reference/grid/#line-names](https://tympanus.net/codrops/css_reference/grid/#line-names), the code sample refers to a column-breadth of 250px, but the diagram shows 150px. The same issue exists for row-height: the code sample says 100px, the diagram says 50px. This is a small issue, but potentially confusing I think.

**Comment by crnacura** [comment]
Thank you, the code sample is now fixed!
