### ISSUE TITLE
scope pseudo-selector article mixes it with scoped attribute

### ISSUE THREAD

**Issue by mestaritonttu** [codrops/css-reference-issues#90]
See the Browser support section: https://tympanus.net/codrops/css_reference/scope/
It is referring to the scoped attribute, which was removed.
The :scope pseudo selector is still in the spec: https://www.w3.org/TR/selectors-4/#the-scope-pseudo

**Comment by crnacura** [comment]
Thank you @mestaritonttu for pointing that out! We've fixed that section now.
