### ISSUE TITLE
Update link from Firefox Nightly to Firefox on subgrid entry

### ISSUE THREAD

**Issue by huijing** [codrops/css-reference-issues#92]
Now that Firefox 71 has shipped, should we update the link to say Firefox instead of Firefox Nightly?

<img width="786" alt="Screenshot 2019-12-06 at 8 17 29 AM" src="https://user-images.githubusercontent.com/1461498/70285140-6f538580-1801-11ea-9b97-f766c95898dc.png">

**Comment by crnacura** [comment]
Yes, definitely! Just updated it.  :)
