### ISSUE TITLE
dead link 

### ISSUE THREAD

**Issue by stevenkuipers** [codrops/css-reference-issues#93]
The article on the empty pseudoclass selector: https://tympanus.net/codrops/css_reference/empty/ contains a link to a page that no longer exists: http://demosthenes.info/blog/692/Vanishing-Acts-The-CSS-empty-Selector

**Comment by crnacura** [comment]
It's working for me: http://thenewcode.com/692/Vanishing-Acts-The-CSS-empty-Selector Maybe it was a temporary issue?

**Comment by stevenkuipers** [comment]
I'm being redirected here: [http://thenewcode.com/blog/692/Vanishing-Acts-The-CSS-empty-Selector](http://thenewcode.com/blog/692/Vanishing-Acts-The-CSS-empty-Selector), which lands you on a 404 page.

**Comment by crnacura** [comment]
Got a 404 now, too :( Thanks for checking again, I will remove the link.
