### ISSUE TITLE
'left' should be replaced by 'right' in code example

### ISSUE THREAD

**Issue by ghost** [codrops/css-reference-issues#94]
On these pages:
http://tympanus.net/codrops/css_reference/transform/#section_translate
https://tympanus.net/codrops/css_reference/translate/

One of the current examples is the following:
`transform: translate(50%, 10%); /* translates the element by 50% of its width to the left, and 10% of its height to the bottom */`

I think the correct example would be this:
`transform: translate(50%, 10%); /* translates the element by 50% of its width to the right, and 10% of its height to the bottom */`

left --> right

Thanks! :)

**Comment by crnacura** [comment]
Thank you, all fixed now!
