### ISSUE TITLE
'ax' should be replaced by 'ay'

### ISSUE THREAD

**Issue by ghost** [codrops/css-reference-issues#95]
This page:
https://tympanus.net/codrops/css_reference/skewy/

Says the following:
> It takes an angle ay as a value.

And then the following:
> 90deg – ax

In the latter one, ax should be replayed by ay, such as follows:
> 90deg – ay

ax --> ay

Thanks! :)

**Comment by crnacura** [comment]
Thanks for catching this! It has been corrected now :)
