### ISSUE TITLE
Illegible code snippets in article due to contrast issues

### ISSUE THREAD

**Issue by smith558** [codrops/css-reference-issues#98]
The code snippets in the article https://tympanus.net/codrops/css_reference/grid/ are barely legible and almost illegible with night mode enabled on many monitors.

![image](https://github.com/codrops/css-reference-issues/assets/44023416/4d03a1f9-e8e1-436f-abcd-0d1b72b70819)

It would be helpful if they were updated to the font colour such as the one used in a single snippet in the article at https://tympanus.net/codrops/css_reference/grid/#section_grid-auto-flow. This one is clearly legible on all monitors.

![image](https://github.com/codrops/css-reference-issues/assets/44023416/3af2d9e6-c7b2-45cd-af17-e2ef66e0de43)

**Comment by smith558** [comment]
The other articles already seem to be using other font colours, e.g. https://tympanus.net/codrops/css_reference/left_pseudo-class/

**Comment by crnacura** [comment]
Thank you for pointing that out! We've had some inconsistent markup which lead to this color change but I've fixed it now and it should work for all entries. Very sorry it was so unreadable!

**Comment by smith558** [comment]
No worries. Looks way better now. 🙂
